name: Extract layer from France

on: [push]

jobs:
  dowload:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: byrnedo/docker-alpine-curl@master
    - name: Donload France OSM pbf
      run: curl https://download.openstreetmap.fr/extracts/europe/france-latest.osm.pbf --output france-latest.osm.pb
      
    - uses: pfisterer/openstreetmap-osmosis-docker@master
    - name: Run a multi-line script
      run: osmosis --read-pbf france-latest.osm.pbf --bounding-box top=49.26 left=1.425 bottom=48.1 right=3.58 --write-pbf planet-idf.osm.pbf
